import { Montserrat, Montserrat_Alternates } from 'next/font/google'

import Providers from '@/app/providers'
import Header from '@/components/Header/Header'

import type { Metadata } from 'next'

import './globals.css'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const montserratAlternates = Montserrat_Alternates({
  subsets: ['latin'],
  variable: '--font-montserrat-alternates',
  style: ['normal', 'italic'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${montserratAlternates.variable} antialiased h-[2200px]`}
      >
        <Providers>
          <Header />
          <div className='flex justify-center w-full'>
            <p className='font-bold text-accent hover:text-accent/80'>Learn Tailwind</p>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
